sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
install:
  - bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
    - master
env:
  global:
    secure: wVXnu7XU/GwBonM3SdDHrtALodjiKv2jJ/N+BSmHSDuRpEXDul7TYi2LwbbANh0Or9nuMoPYRfYGsccIekN4/woRDkWRgPaclweY6OErW32A4FhhEomYbiYK/PAyRlOqtfAxbD6PFwVRXGpxQVe/UxuLP3VQb/Yjk/JL05zSL1Km4rwO5X8MB09lhC709EDD+mbaZFydyPCe6bogbIpzYudwqL/nMDGm+FztCbmhxezwe6R+xq/P6UMwO6RJ1tZBETYaV/eyVmCzlg6y7yKrazLDAjQe3ZG3D9gJdZfCg5y+HQkk9gFa4UXM8ZfOuwIGunXlCQHqNGYcaYyKAjlXjckSQHFeXMwNnaI3T0QTLObnLZK4XNJvaxD3U9EUiThGWkS0N0AAj2YTbgRRN4aF6k31HWyWIRg/3imMb5MGj5MNXowAO4L2METfKko2xVwTZtgn8nKuvU2O8viwQow6w9D1jqtXqmh1GIZwXioPuqRfsROyXyc7FMYTH+pct+Ae7+k+7f/4EpPTY4W6NlgSHzOOiKvRpNkLcFL7ap2aWIXlyNSRI4bqqTlOKYN8or3ty4mni1F5BIl2n+CjiJfjWXOkCV28uqwbxBVPzf7sM2482+GUN865RPkbs3fz67BKUpIJrc7sZdJV7kj+jS31NdXZJ0t4MOKlUV9lLKcg2MY=
