sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
install:
  - bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
    - master
env:
  - secure: "vvYp6RXgv4e4vl3oAc2lUuiPTcZsWmTsIBFX9qeKAEgFirk7Malc6d75jT7ycYqShfKjep4eMYnHf2MxhzjaHjwFsbkd719UtuubviuHP0LxJp8GLITqfyvTo2ZZoTKfHz76EgVnpceqiquoPvr8uy3ce4fJjAipY7yzINQOMQcfoYPuUygUWZeA3GpnfNL2BhvW9cPXGSdW9oMuxXzgfQ8m0uui6zRzGFh+BU5NZzBgP+6MhjY/bF4Hp1xmM0MQ2wLXLAVXbtpKSFLNQ1QHvPK07JKOkFI2FUDu7uqTNLadvsf/2dakQ+smBcctwxSpu4agUTZOReDcBOWfHJAyPjGAdZ/60NiOwJ4sxm5dd1ouGdZNmgQ2sF0VD6aV46VZ++j9zCUvO9w7wa/Ed2pFKBH7G3bDOnr68Y6Qb7WXF9gnKhzVUERdQHN1g4rwuB+dpIxyiIRWo+pJ3bAZYW0FFYQHJpyrGXKFNXkI8X8N6dPTpSZjWMeh5sW3lkbUa/PjBQkEdbcpDmBuqmTA4g89WFacpvPtZ9CKuKecQgIZZQeUFs6F3PYitBQrJ6JEvsqFS8DbYjTPgsDxEgSo5VdLWLealO+DJH7d/2QmetV052WRQh5MkgLZWZf1iFT/VrjMiAUy89PFboKzFle9IGZD//i+lhokLhfD9sB1yn4JxuE="
