sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
install:
  - bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
    - master
env:
  - secure: "sKCzhuJzpVc93AlmBgGwv/M+iXzpE+Z8kleGDgZZwabLGiSZJi8/N68HiWdKddf9OsL92iAPP4RTzD9BCBVjv9r7EFOCcObrfkyGOBG0Y8BzWYu3TEp1/ebr/qqr66UqPXNL4lywY5gd4JyXhmxi+Qn2nrwj6R3Hro0AiM4WcH91gemYk8xAYxoW4tkvo4oJBQbvJYWDvz0YIHQXDHkOHH/GXfuEwbV9/kEcAlIkiSllX5EUapZWqQ6Tts08tf7bfOOvMRPB1h0T5FMlg79xsHelpk8sqYmG5Ra8eDuquMpDIjNkk2mBm/p8APC9ZsDTke5Oy2p9KTRy8Q9YvzKlJDgFYrrCb50ZqHwJ9exxYDq9apiX+c3svV5svEu3mpZ1EqUK1Sl4tcK5V+wXpPycXTQ4gNoGQKKB84DSuT9Ttn2xpjt4uAyIMxoHr+25c0MFjA4qE2iuFCJalSbzSeIj6rs+TeLtGv2PaSRHtoIteZEKTSMlGpwfhOLMfkHQu6PLWDbITc7TsGqXScsRGdWxHWUr2jG1gACY6ajpcJn0p1f3HXL/bq6W1tXvW8Kivi2/j5zwapN/n+39i0/9WVxrScQ/ZUj+DLfvB2IocDEvWqjpjfKazm6AfnKolIVP/2ANW5Bwf9ssarzw4YKmciPYixpv8I4EYLSQn7JIW3+Qpvg="
