# Site settings
name: "Doss-Gollin Group @ Rice CEVE"
title: Doss-Gollin Research Group
#subtitle: adaptive infrastructure for resilient communities
subtitle:
email: jdossgollin@rice.edu
description: "The Doss-Gollin Research Group at Rice University (Starting 2021)"
baseurl: ""
url: "https://dossgollin-lab.github.io"
permalink: /:categories/:title.html
office: 215 Ryon Laboratory
twitter: jdossgollin
github: jdossgollin
labguide: https://dossgollin-lab.github.io/lab-guide

# logos and images to use
logo_cover: /assets/img/logos/header-rpy.jpg
logo_logo: /assets/img/logos/james.jpg
logo_james: /assets/img/logos/james.jpg
logo_icon: /assets/img/logos/logo.ico
logo_ricelogo: /assets/img/logos/rice.jpg
logo_labgroup: /assets/img/logos/header-rpy.jpg
logo_research: /assets/img/research/causal-chain.png

# RSS
rss_path: feeds/
rss_name: rss.xml

# Settings for deploy rake task
safe: False
lsi: False
username: dossgollin-lab
repo: dossgollin-lab.github.io
branch: master
destination: _site
production_url: https://dossgollin-lab.github.io
source_url: https://github.com/dossgollin-lab/dossgollin-lab.github.io/

# Page Set
pages_list:
  About: "/about"
  Feed: "/atom.xml"

#exclude
exclude:
  - "scripts"
  - "README.md"
  - ".DS_Store"
  - "assets/less/"
  - "vendor"
  - "Makefile"

# gems and other configs
plugins_dir: "_plugins"
plugins:
  - jekyll-scholar

scholar:
  style: decision-sciences
  source: _bibliography
  bibliography: library.bib
  bibliography_template: bib
  sort_by: date,year,month
  order: descending
  bibliography_list_tag: div
  bibliography_item_tag: div
