# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: "en-us"
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: James Doss-Gollin
description: Climate, Infrastructure, Decision-Making
cover: assets/images/header-bg.jpg
logo: assets/images/james.jpg
logo_dark: assets/images/james.jpg
favicon: assets/images/james.jpg
production_url: https://jdossgollin.github.io/
source_url: https://github.com/jdossgollin/jdossgollin.github.io/
CNAME: jamesdossgollin.me #add cname for website to be created

# Social info
navigation: True # show the navbar links
# twitter: jdossgollin # replace by your username

# Permalinks
permalink: /:title

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed, jekyll-scholar]

feed:
  path: feed.xml

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
  - script/

include: [_pages]

scholar:
  style: decision-sciences
  source: ./_bibliography
  bibliography: library.bib
  bibliography_template: bib
  sort_by: year
  order: descending

# allow future posts per https://github.com/jekyll/jekyll/issues/6536
future: true
