project:
  type: website
  preview:
    port: 4200

website:
  page-navigation: true
  title: "AI for Climate Risk & Resilience @ Rice"
  site-url: https://ai4climaterrr.rice.edu
  repo-url: https://www.github.com/dossgollin-lab/ai4climaterrr
  repo-actions: [issue]
  open-graph: true
  favicon: _assets/img/logos/logo.ico

  search:
    location: navbar
    type: overlay

  page-footer:
    left: |
      View the source [on GitHub]({{< var website.repo-url >}})

format:
  html:
    theme: [sandstone, _assets/theme/theme-rice.scss]
    toc: false
    anchor-sections: true
    code-overflow: wrap
    citations-hover: true
    code-annotations: hover
    html-math-method: mathjax
    date-format: long

# references
bibliography: references.bib
csl: _assets/references/american-geophysical-union.csl

link-external-newwindow: true
