---
title: "AI4ClimateRRR at AGU 2024"
date: 2024-12-05
---

Researchers from the AI4ClimateRRR cluster will be at AGU 2024 in Washington, DC.!
We look forward to seeing you there.

### Monday

- eLightning Session: [NH14C - Multihazard Flood Modeling: From Inland to Coast I](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/240862)
- Talk: [PP11A-02A holistic evaluation of proxy/model disagreement in tropical Africa during the Deglaciation and Holocene for GDGT lake temperature records](PP11A-02A holistic evaluation of proxy/model disagreement in tropical Africa during the Deglaciation and Holocene for GDGT lake temperature records )

### Tuesday

- Poster Session: [NH23A Advancements in Urban Water Systems for Resilient, Sustainable, and Equitable Communities](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/226684)
- Poster: [GC23D-0279 Graph Residual Transformer + Gated Recurrent Unit (GRU) for Global Numerical Weather Prediction](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1709468)
- Poster: [PP21C-0473 Changes in Texas Rainfall Characteristics During the Last Deglaciation in Speleothem Proxies and Water Isotope-enabled Model Simulations](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1621742)
- Talk: [GC24H-01 Assessing and Managing Climate Risks to Electricity Systems in an Era of Climate Change and Energy Transition](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1711820)
- Talk: [H23U-08 Improving Vegetation Realism in Earth System Models through Satellite Observations](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1745761)
- Talk: [NG23A-01 Water isotopes, climate variability, and the hydrological cycle: recent advances and new frontiers](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1528712)
- Talk: [NH23G-06 TxRAIN-Observational: A Hierarchical Bayesian Spatial Framework to Assess Nonstationary Rainfall Intensity, Frequency, and Duration in Texas](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1624973)

### Thursday

- Oral Session: [PP44B Water Isotope Systematics: Improving Modern and Paleoclimate Interpretations](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/232087)
- Poster Session: [NH41C Hybrid Modeling and Digital Twin Systems for Flood Hazard Prediction and Risk Assessment at Different Spatial Scales](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/224843)
- Poster Session: [NH41D Multihazard Flood Modeling: From Inland to Coast](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/224642)
- Poster: [NH41C-2328P  luvial Flood Emulation with Hydraulics-informed Message Passing](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1638085)
- Poster: [NH43C-2415 Isolating Contributing Factors of Coastal Water Levels for Improved Probabilistic Synthetic Data: An Innovative Approach](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1711916)
- Poster: [PP41E-0373 Recent Flooding in the Middle East in the Context of the Last Millennium](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1733887)
- Talk: [PP41B-02 Hydroclimate Extremes Link Mainland Southeast Asia and Central Asia over the Past Millennium](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1558619)
- Talk: [PP42B-04 Last Millennium Changes in Mississippi River Basin Hydroclimate Driven by Anthropogenic Forcing and Atmospheric Dynamics](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1568143)
- Talk: [A43Z-07 Seamless integration of tropical cyclone winds with large-scale numerical weather prediction models for improved hazard assessment](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1667697)

### Friday

- Oral Session: [PP54B Water Isotope Systematics: Improving Modern and Paleoclimate Interpretations](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/232098)
- Poster Session: [PP51F Water Isotope Systematics: Improving Modern and Paleoclimate Interpretations](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/224838)
- Talk: [GC54B-01 Advancing Water and Food Security with AI and Hyper-Resolution Soil Moisture Data](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1737431)
- Talk: [NH51A-01 Advancing Urban Flood Hazard Characterization through Machine Learning: Challenges and Opportunities](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1711605)
