---
title: "Coverage: Rice engineers develop AI system for real-time sensing of flooded roads"
date: 2024-08-26
---

Rice University recently highlighted research from our AI for Climate Risk and Resilience at Rice (AI4CRRR) cluster.
The feature story covers work led by cluster co-PI Jamie Padgett, focusing on an AI-driven system for real-time sensing of flooded roads.

The featured study introduces OpenSafe Fusion, an automated data fusion framework that leverages existing public data sources to predict road flooding conditions.
By combining insights from traffic alerts, cameras, and traffic speed data, the system demonstrated promising results in tests using historical data from Hurricane Harvey.
We hope this approach can significantly advance flood situational awareness without requiring substantial investment in new infrastructure, potentially improving public safety and mobility during increasingly frequent urban flooding events.

For more details, read the [full story](https://news.rice.edu/news/2024/rice-engineers-develop-ai-system-real-time-sensing-flooded-roads) or access the [research study](https://www.sciencedirect.com/science/article/abs/pii/S095183202400440X?via%3Dihub).