name: Ruby

on:
  repository_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    # run only on upstream, not on downstream
    if: github.repository == 'dossgollin-lab/dossgollin-lab.github.io'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true
      - name: Update submodules
        run: |
          cd _bibliography/
          git branch -u origin/master master
          cd ..
          git submodule update --recursive --remote
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.66.1
        with:
          ruby-version: 3.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build site
        run: |
          set -xo pipefail
          rm -rf _site/*
          gem install bundler
          bundle install
          bundle exec jekyll build
      - name: Commit and push
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
          CLEAN: true
          GIT_CONFIG_NAME: "Github Action"
          GIT_CONFIG_EMAIL: actions@github.com
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
