on:
  repository_dispatch:
  push:
    branches: [master]

name: Render and Publish

# you need these permissions to publish to GitHub pages
permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # run only on upstream, not on downstream
    if: github.repository == 'dossgollin-lab/dossgollin-lab.github.io'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2=

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
